src/java/manejadores/departamentoBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manejadores;

import Util.Util;
import dao.departamentoDAO;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.SelectItem;
import modelo.Departamento;

/**
 *
 * @author Josermando
 */
@ManagedBean(name = "departamento")
@SessionScoped
public class departamentoBean {

    private Departamento depto;
    @EJB
    private departamentoDAO dao;
    private List<Departamento> listado;
    public boolean updateItem;
    
    public departamentoBean() {
        getDepto();
        depto.setEstado(1);
    }
//    @PostConstruct
//    public void init(){
//        depto.setEstado(1);
//    }
//    
    //Getters and Setters

    public Departamento getDepto() {
        if(depto == null)
            depto = new Departamento();
        return depto;
    }

    public void setDepto(Departamento depto) {
        this.depto = depto;
    }

    public departamentoDAO getDao() {
        return dao;
    }

    public void setDao(departamentoDAO dao) {
        this.dao = dao;
    }

    public List<Departamento> getListado() {
        listado = getDao().buscarTodosDeptos();
        return listado;
    }

    public void setListado(List<Departamento> listado) {
        this.listado = listado;
    }

    public boolean isUpdateItem() {
        return updateItem;
    }

    public void setUpdateItem(boolean isEditable) {
        this.updateItem = isEditable;
    }
    
    
    
    //Metodos CRUD
    public String guardarDepto(){
        getDao().guardar(depto);
        setUpdateItem(false);
        clear();
        return "/departamento.xhtml?faces-redirect=true";
    }
    
    public void actualizar(){
        getDao().actualizar(depto);
        setUpdateItem(false);
        clear();
    }
    
    public void actualizarDepto(Departamento depto){
        this.depto = depto;
        setUpdateItem(true);
        System.out.println("Funciono??");
    }
    
    public void eliminarDepto(Departamento depto){
        this.depto = depto;
        setUpdateItem(true);
        eliminar();
        System.out.println("Eliminando");
    }
    
    public void eliminar(){
        getDao().suspender(depto);
        getDao().actualizar(depto);
        setUpdateItem(false);
        clear();
    }
    
    public void clear(){
        depto = null;
    }
    public SelectItem[] getItemsAvailableSelectOne() {
        return Util.getSelectItems(getDao().buscarTodos(), true);
    }
    
     public SelectItem[] getItemsAvailableSelectMany() {
        return Util.getSelectItems(getDao().buscarTodos(), false);
    }
     
    @FacesConverter(forClass = Departamento.class)
    public static class DepartamentoConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            departamentoBean controller = (departamentoBean) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "departamento");
            return controller.getDao().buscar(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Departamento) {
                Departamento o = (Departamento) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Departamento.class.getName());
            }
        }

    }
}

src/java/manejadores/empleadoBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manejadores;

import Util.Util;
import dao.empleadoDAO;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.SelectItem;
import modelo.Empleado;

/**
 *
 * @author Josermando
 */
@ManagedBean(name = "empleado")
@SessionScoped
public class empleadoBean {

    private Empleado emp;
    @EJB
    private empleadoDAO dao;
    private List<Empleado> listado;
    private List<Empleado> filtro;
    private boolean updateItem;
    
    public empleadoBean() {
        getEmp();
        emp.setEstado(1);
    }
    
    //Getters and Setters

    public Empleado getEmp() {
        if(emp == null)
            emp = new Empleado();
        return emp;
    }

    public void setEmp(Empleado emp) {
        this.emp = emp;
    }

    public empleadoDAO getDao() {
        return dao;
    }

    public void setDao(empleadoDAO dao) {
        this.dao = dao;
    }

    public List<Empleado> getListado() {
        listado = getDao().buscarTodosEmpleados();
        return listado;
    }

    public void setListado(List<Empleado> listado) {
        this.listado = listado;
    }

    public boolean isUpdateItem() {
        return updateItem;
    }

    public void setUpdateItem(boolean isEditable) {
        this.updateItem = isEditable;
    }

    public List<Empleado> getFiltro() {
        return filtro;
    }

    public void setFiltro(List<Empleado> filtro) {
        this.filtro = filtro;
    }
    
    //Metodos CRUD
    
    public String guardarEmpleado(){
       getDao().guardar(emp);
       setUpdateItem(false);
       clear();
       return "/empleado.xhtml?faces-redirect=true";
    }
    public void actualizar(){
        getDao().actualizar(emp);
        setUpdateItem(false);
        clear();
    }
    public void actualizarEmpleado(Empleado emp){
        this.emp = emp;
        setUpdateItem(true);
        System.out.println("Funciono en Empleado?");
    } 
    
    public void eliminarEmpleado(Empleado emp){
        this.emp = emp;
        setUpdateItem(true);
        eliminar();
        System.out.println("Eliminado");
    }
    
    public void eliminar(){
        getDao().suspender(emp);
        getDao().actualizar(emp);
        setUpdateItem(false);
        clear();
    }
    
    public void clear(){
        emp = null;
    }
    
    
    public SelectItem[] getItemsAvailableSelectMany() {
        return Util.getSelectItems(getDao().buscarTodos(), false);
    }
     
     @FacesConverter(forClass = Empleado.class)
    public static class EmpleadoConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            empleadoBean controller = (empleadoBean) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "empleadoBean");
            return controller.getDao().buscar(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Empleado) {
                Empleado o = (Empleado) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Empleado.class.getName());
            }
        }

    }
    
    
}

web/departamento.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">

    <body>

        <ui:composition template="./template.xhtml">
            <ui:define name="content">
                <h1 class="h2">Departamentos</h1>

                <h:form id="frmNuevo">
                    <p:commandButton id="btnNuevo" value="Nuevo Departamento" onclick="new_depto.show()" type="button"/>
                    <p:dialog id="dlg" widgetVar="new_depto" hideEffect="true" header="#{!departamento.updateItem ? 'Nuevo Departamento' : 'Editar Departamento'}">
                        <h:panelGrid columns="2" style="margin-bottom:10px" cellpadding="5">
                            <p:outputLabel for="nombre" value="Nombre"/>
                            <p:inputText id="nombre" value="#{departamento.depto.nombre}"/>
                            <p:outputLabel for="descripcion" value="Descripcion"/>
                            <p:inputText id="descripcion" value="#{departamento.depto.descripcion}"/>
                            <p:inputText id="estado" value="#{departamento.depto.estado}" rendered="false"/>
                        </h:panelGrid>
                        <p:commandButton action="#{departamento.guardarDepto()}" value="Guardar" rendered="#{!departamento.updateItem}" update=":frmNuevo"/>
                        <p:commandButton action="#{departamento.actualizar()}" value="Editar" rendered="#{departamento.updateItem}" update=":frmNuevo"/>
                    </p:dialog>
                
                    <p:dataTable value="#{departamento.listado}" var="depto" paginator="true" rows="5" tableStyleClass="table table-responsive"
                                 paginatorPosition="bottom">
                        <p:column headerText="Nombre">
                            <p:outputLabel value="#{depto.nombre}"/>
                        </p:column>
                        <p:column headerText="Descripcion">
                            <p:outputLabel value="#{depto.descripcion}"/>
                        </p:column>
                        <p:column rendered="#{usuario.user.rol.equals('ADMIN')}">
                            <p:commandButton id="btnEditar" icon="ui-icon-edit" action="#{departamento.actualizarDepto(depto)}" update=":frmNuevo" oncomplete="new_depto.show()"/>
                        </p:column>
                        <p:column rendered="#{usuario.user.rol.equals('ADMIN')}">
                            <p:commandButton id="btnEliminar" icon="ui-icon-close" action="#{departamento.eliminarDepto(depto)}" update=":frmNuevo"/>
                        </p:column>
                    </p:dataTable>
                </h:form>
                    
            </ui:define>
        </ui:composition>
    </body>
</html>

web/empleado.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <body>

        <ui:composition template="./template.xhtml">
            <ui:define name="content">
                <h1 class="h2">Empleados</h1>
                <h:form id="frmNuevo">
                    <p:commandButton id="btnNuevo" value="Nuevo Empleado" onclick="new_emp.show()" type="button"/>
                    <p:dialog id="dlg" widgetVar="new_emp" hideEffect="true" header="#{!empleado.updateItem ?'Nuevo Empleado': 'Editar Empleado'}">
                        <h:panelGrid columns="2" style="margin-bottom:10px" cellpadding="5">
                            <p:outputLabel for="nombre" value="Nombre"/>
                            <p:inputText id="nombre" value="#{empleado.emp.nombre}"/>
                            <p:outputLabel for="apellido" value="Apellido"/>
                            <p:inputText id="apellido" value="#{empleado.emp.apellido}"/>
                            <p:outputLabel for="cedula" value="Cedula"/>
                            <p:inputMask mask="999-9999999-9" id="cedula" value="#{empleado.emp.cedula}"/>
                            <p:outputLabel for="posicion" value="Posicion"/>
                            <p:inputText id="posicion" value="#{empleado.emp.posicion}"/>
                            <p:outputLabel for="sueldo" value="Sueldo"/>
                            <p:inputText id="sueldo" value="#{empleado.emp.sueldo}"/>
                            <p:outputLabel for="depto" value="Departamento"/>
                            <p:selectOneMenu id="depto" value="#{empleado.emp.idDepartamento}">
                                <f:selectItems value="#{departamento.itemsAvailableSelectOne}"/>
                            </p:selectOneMenu>
                            <p:inputText id="estado" value="#{empleado.emp.estado}" rendered="false"/>
                        </h:panelGrid>
                        <p:commandButton action="#{empleado.guardarEmpleado()}" value="Guardar" rendered="#{!empleado.updateItem}" update=":frmNuevo"/>
                        <p:commandButton action="#{empleado.actualizar()}" value="Guardar" rendered="#{empleado.updateItem}" update=":frmNuevo"/>
                    </p:dialog>

                    <p:dataTable value="#{empleado.listado}" var="emp" paginator="true" rows="5"
                                 tableStyleClass="table table-hover table-responsive" 
                                 emptyMessage="No hay empleados disponibles"
                                 paginatorPosition="bottom">
                        <p:column headerText="Nombre">
                            <p:outputLabel value="#{emp.nombre}"/>
                        </p:column>
                        <p:column headerText="Apellido">
                            <p:outputLabel value="#{emp.apellido}"/>
                        </p:column>
                        <p:column headerText="Cedula">
                            <p:outputLabel value="#{emp.cedula}"/>
                        </p:column>
                        <p:column headerText="Departamento">
                            <p:outputLabel value="#{emp.idDepartamento.nombre}"/>
                        </p:column>
                        <p:column  rendered="#{usuario.user.rol.equals('ADMIN')}">
                            <p:commandButton id="btnEditar" icon="ui-icon-pencil" action="#{empleado.actualizarEmpleado(emp)}" update=":frmNuevo" oncomplete="new_emp.show()"/>
                        </p:column>
                        <p:column  rendered="#{usuario.user.rol.equals('ADMIN')}">
                            <p:commandButton id="btnEliminar" icon="ui-icon-close" action="#{empleado.eliminarEmpleado(emp)}" update=":frmNuevo"/>
                        </p:column>
                    </p:dataTable>
                </h:form>
            </ui:define>

        </ui:composition>

    </body>
</html>

web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <body>

        <ui:composition template="./template.xhtml">

            <ui:define name="content">
                    
                <h:link  value="Departamentos" outcome="departamento"/>
                <br/>
                <h:link  value="Empleados" outcome="empleado"/>
                <br/>
                <h:link  value="Nomina" outcome="nomina"/>
            </ui:define>

        </ui:composition>

    </body>
</html>

web/login.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
     
        <!--<h:outputScript name="/js/jquery-1.8.3.js"/>-->
        <h:outputStylesheet name="./css/bootstrap.css"/>
        <h:outputStylesheet name="/css/custom.css"/>
        <h:outputScript name="./js/bootstrap.js"/>
        <title>Nomina</title>
    </h:head>
    <h:body>
        <div class="container">
            <h:form styleClass="form-signin">
                <h2 class="form-signin-heading">Por favor inicia sesion</h2>
                <p:outputLabel value="Usuario"/>
                <p:inputText id="usuario" value="#{usuario.username}" placeholder="Nombre de Usuario" styleClass="form-control"/>
                <p:outputLabel value="Password"/>
                <p:inputText id="pass" value="#{usuario.password}" placeholder="Password" styleClass="form-control" required="true" requiredMessage="Escriba su pass"/>
                <p:message for="pass" class="error_message"/>
                <br/>
                <p:commandButton id="btnAcceder" value="Acceder" styleClass="btn btn-lg btn-primary btn-block" action="#{usuario.autenticar()}"/>
            </h:form>
        </div>
    </h:body>
</html>

web/nomina.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <body>

        <ui:composition template="./template.xhtml">

            <ui:define name="content">
                <h:form id="frmTable">
                    <h1 class="h2">Nomina</h1>
                    <p:dataTable value="#{empleado.listado}" var="emp" 
                                 tableStyleClass="table table-hover table-responsive"
                                 paginator="true" widgetVar="nominaTable"
                                 paginatorPosition="bottom">
                       <f:facet name="header">  
                            <p:outputPanel>  
                                <h:outputText value="Buscar por Departamento:" />  
                                <p:inputText id="globalFilter" onkeyup="nominaTable.filter()" style="width:150px" />  
                            </p:outputPanel>  
                        </f:facet>
                        <p:column headerText="Nombre Completo"> 
                            <p:outputLabel value="#{emp.nombre} #{emp.apellido}"/>
                        </p:column>
                        <p:column headerText="Departamento" filterBy="#{emp.idDepartamento.nombre}"
                                  filterMatchMode="contains">
                            <p:outputLabel value="#{emp.idDepartamento.nombre}"/>
                        </p:column>
                        <p:column headerText="Posicion">
                            <p:outputLabel value="#{emp.posicion}"/>
                        </p:column>
                        <p:column headerText="Sueldo Bruto">
                            <p:outputLabel value="#{emp.sueldo}">
                                <f:convertNumber type="currency" currencySymbol="RD$" />
                            </p:outputLabel>    
                        </p:column>
                        <p:column headerText="SFS">
                            <p:outputLabel value="#{emp.sfs}">
                                <f:convertNumber type="currency" currencySymbol="RD$" />
                            </p:outputLabel>
                        </p:column>
                        <p:column headerText="ARS">
                            <p:outputLabel value="#{emp.ars}">
                                <f:convertNumber type="currency" currencySymbol="RD$" />
                            </p:outputLabel>
                        </p:column>
                        <p:column headerText="Sueldo Neto">
                            <p:outputLabel value="#{emp.sueldoNeto}">
                                <f:convertNumber type="currency" currencySymbol="RD$" />
                            </p:outputLabel>    
                        </p:column>
                    </p:dataTable>
                </h:form>
            </ui:define>

        </ui:composition>

    </body>
</html>

web/template.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <!--<h:outputScript name="/js/jquery-1.8.3.js"/>-->
        <h:outputStylesheet name="./css/bootstrap.css"/>
        <h:outputStylesheet name="/css/custom.css"/>
        <h:outputScript name="./js/bootstrap.js"/>
        <title>Nomina</title>
        <f:event listener="#{usuario.verificarAuth()}" type="preRenderView"></f:event>
    </h:head>

    <h:body>
<!-- Navbar -->
            <div id ="navbar" class="nav navbar-inverse navbar-static-top" role="navigation">
                <div class="container">
                    <div class ="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse" rendered="#{usuario.loggedIn == true}">
                        <ul class="nav navbar-nav">
                            <li><h:link outcome="index">Inicio</h:link></li>
                            <li><h:link outcome="departamento">Departamentos</h:link></li>
                            <li><h:link outcome="empleado">Empleados</h:link></li>
                            <li><h:link outcome="nomina">Listado</h:link></li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <h:form>
                                <li style="color: white">Bienvenido <p:outputLabel value="#{usuario.username}"/> </li>
                                <li><h:commandLink action="#{usuario.logout}">Desconectarse</h:commandLink></li>
                            </h:form>
                        </ul>
                    </div>
                </div>
            </div>
        
        <div class="container">
            <ui:insert name="content">
                
            </ui:insert>
        </div>

    </h:body>

</html>